title: f0ld.space
email: me@f0ld.space
description: >-
  My personal website for fun things!
baseurl: "/"
url: "https://f0ld.space"
github_username: f0ldspace
# Build settings
remote_theme: f0ldspace/jekyll-theme-console
# theme: jekyll-theme-console
style: light
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
header_pages:
  - index.html
  - stats.html
  - posts.html
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
