title: f0ld.space
email: me@f0ld.space
description: >-
  A simple Jekyll blog hosted on GitHub Pages.
baseurl: "/"
url: "https://f0ld.space"
github_username: f0ldspace
# Build settings
remote_theme: f0ldspace/jekyll-theme-console
style: light
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
header_pages:
  - index.html
  - reading.md
  - anki.md
  - posts.html
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
